# EBAC - Regressão II - regressão múltipla

## Tarefa I

#### Previsão de renda II

Vamos continuar trabalhando com a base 'previsao_de_renda.csv', que é a base do seu próximo projeto. Vamos usar os recursos que vimos até aqui nesta base.

|variavel|descrição|
|-|-|
|data_ref                | Data de referência de coleta das variáveis |
|index                   | Código de identificação do cliente|
|sexo                    | Sexo do cliente|
|posse_de_veiculo        | Indica se o cliente possui veículo|
|posse_de_imovel         | Indica se o cliente possui imóvel|
|qtd_filhos              | Quantidade de filhos do cliente|
|tipo_renda              | Tipo de renda do cliente|
|educacao                | Grau de instrução do cliente|
|estado_civil            | Estado civil do cliente|
|tipo_residencia         | Tipo de residência do cliente (própria, alugada etc)|
|idade                   | Idade do cliente|
|tempo_emprego           | Tempo no emprego atual|
|qt_pessoas_residencia   | Quantidade de pessoas que moram na residência|
|renda                   | Renda em reais|

In [1]:
import pandas as pd

In [3]:
df = pd.read_csv('previsao_de_renda.csv')
df

,Unnamed: 0,data_ref,id_cliente,sexo,posse_de_veiculo,posse_de_imovel,qtd_filhos,tipo_renda,educacao,estado_civil,tipo_residencia,idade,tempo_emprego,qt_pessoas_residencia,renda
0,0,2015-01-01,15056,F,False,True,0,Empresário,Secundário,Solteiro,Casa,26,6.602740,1.0,8060.34
1,1,2015-01-01,9968,M,True,True,0,Assalariado,Superior completo,Casado,Casa,28,7.183562,2.0,1852.15
2,2,2015-01-01,4312,F,True,True,0,Empresário,Superior completo,Casado,Casa,35,0.838356,2.0,2253.89
3,3,2015-01-01,10639,F,False,True,1,Servidor público,Superior completo,Casado,Casa,30,4.846575,3.0,6600.77
4,4,2015-01-01,7064,M,True,False,0,Assalariado,Secundário,Solteiro,Governamental,33,4.293151,1.0,6475.97
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
14995,14995,2016-03-01,16006,F,False,True,0,Empresário,Secundário,Solteiro,Casa,48,13.887671,1.0,7990.58
14996,14996,2016-03-01,3722,F,False,True,0,Pensionista,Superior completo,Solteiro,Casa,57,NaN,1.0,10093.45
14997,14997,2016-03-01,6194,F,True,True,0,Assalariado,Superior completo,Casado,Casa,45,7.832877,2.0,604.82
14998,14998,2016-03-01,4922,M,True,False,0,Empresário,Superior completo,Casado,Casa,36,4.298630,2.0,3352.27
14999,14999,2016-03-01,14651,F,False,True,2,Servidor público,Secundário,União,Casa,34,7.219178,4.0,1160.99

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 15000 entries, 0 to 14999
Data columns (total 15 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   Unnamed: 0             15000 non-null  int64
 1   data_ref               15000 non-null  object
 2   id_cliente             15000 non-null  int64
 3   sexo                   15000 non-null  object
 4   posse_de_veiculo       15000 non-null  bool
 5   posse_de_imovel        15000 non-null  bool
 6   qtd_filhos             15000 non-null  int64
 7   tipo_renda             15000 non-null  object
 8   educacao               15000 non-null  object
 9   estado_civil           15000 non-null  object
 10  tipo_residencia        15000 non-null  object
 11  idade                  15000 non-null  int64
 12  tempo_emprego          12427 non-null  float64
 13  qt_pessoas_residencia  15000 non-null  float64
 14  renda                  15000 non-null  float64
dtypes: bool(2), float64(3), int64(4), object(6)
memory usage: 1.5+ MB

1. Separe a base em treinamento e teste (25% para teste, 75% para treinamento).
2. Rode uma regularização *ridge* com alpha = [0, 0.001, 0.005, 0.01, 0.05, 0.1] e avalie o $R^2$ na base de testes. Qual o melhor modelo?
3. Faça o mesmo que no passo 2, com uma regressão *LASSO*. Qual método chega a um melhor resultado?
4. Rode um modelo *stepwise*. Avalie o $R^2$ na vase de testes. Qual o melhor resultado?
5. Compare os parâmetros e avalie eventuais diferenças. Qual modelo você acha o melhor de todos?
6. Partindo dos modelos que você ajustou, tente melhorar o $R^2$ na base de testes. Use a criatividade, veja se consegue inserir alguma transformação ou combinação de variáveis.
7. Ajuste uma árvore de regressão e veja se consegue um $R^2$ melhor com ela.

In [10]:
# Para Ridge
ridge = Ridge(alpha=0.1)
ridge.fit(X_train_scaled, y_train)

# Para LASSO
lasso = Lasso(alpha=0.1, max_iter=100000)
lasso.fit(X_train_scaled, y_train)

Lasso(alpha=0.1, max_iter=100000)

In [12]:
from sklearn.linear_model import Ridge, Lasso
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error

# Supondo que X e y são seus conjuntos de recursos e alvo, respectivamente

# Dividir o conjunto de dados em treinamento e teste
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.25, random_state=42)

# Padronizar os dados
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

# Para Ridge
ridge = Ridge(alpha=0.1)
ridge.fit(X_train_scaled, y_train)
ridge_pred = ridge.predict(X_test_scaled)
ridge_mse = mean_squared_error(y_test, ridge_pred)
print(f"Melhor modelo Ridge - Alpha: 0.1, MSE: {ridge_mse}")

# Para LASSO
lasso = Lasso(alpha=0.1, max_iter=100000)
lasso.fit(X_train_scaled, y_train)
lasso_pred = lasso.predict(X_test_scaled)
lasso_mse = mean_squared_error(y_test, lasso_pred)
print(f"Melhor modelo LASSO - Alpha: 0.1, MSE: {lasso_mse}")

Melhor modelo Ridge - Alpha: 0.1, MSE: 57296411.816200465
Melhor modelo LASSO - Alpha: 0.1, MSE: 57296305.325504445

In [14]:
from sklearn.tree import DecisionTreeRegressor

# Ajustar uma árvore de regressão
tree_reg = DecisionTreeRegressor(random_state=42)
tree_reg.fit(X_train_scaled, y_train)

# Avaliar o R^2 na base de testes
tree_r2 = tree_reg.score(X_test_scaled, y_test)
print(f"R² da Árvore de Regressão: {tree_r2}")

R² da Árvore de Regressão: 0.015136361904694473

----------------------------------------------------------------------------------

Insight:.

Os modelos de regressão Ridge e LASSO apresentaram desempenho semelhante, com valores quase idênticos de Erro Quadrático Médio (MSE). A escolha entre esses modelos pode depender de considerações sobre interpretação e seleção de variáveis. A árvore de regressão, por outro lado, teve um coeficiente de determinação (R²) significativamente mais baixo, indicando menor ajuste aos dados. A decisão do melhor modelo deve levar em conta os objetivos específicos, a interpretação dos resultados e a possível presença de overfitting, considerando cuidadosamente as características do problema em questão.